# Generated by Django 3.1 on 2020-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='ConditionSchema',
        ),
        migrations.AlterField(
            model_name='user',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
