# Generated by Django 3.1 on 2020-10-03 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201003_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditionschema',
            name='related_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='account.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='account.service'),
        ),
    ]
