# Generated by Django 3.1 on 2020-10-04 16:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201004_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/img/avatar.png', null=True, storage=django.core.files.storage.FileSystemStorage(location='static/img'), upload_to=''),
        ),
    ]
