# Generated by Django 3.1 on 2020-10-03 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.service')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=24)),
                ('given_stock', models.CharField(default='', max_length=64)),
                ('got_stock', models.CharField(default='', max_length=64)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('description', models.CharField(default='', max_length=32)),
                ('checked', models.BooleanField(default=False)),
                ('related_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.step')),
            ],
        ),
    ]
