# Generated by Django 3.1 on 2020-10-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20201004_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description_client',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='step',
            name='judgement_description_business',
            field=models.CharField(default='', max_length=256),
        ),
    ]
